
set(XSD_COMMON_OPTIONS
  GENERATE_INLINE
  GENERATE_XML_SCHEMA
  NAMESPACE_REGEX_TRACE
  INCLUDE_WITH_BRACKETS
  INCLUDE_REGEX_TRACE
  EXPORT_XML_SCHEMA
  EXPORT_MAPS
  IMPORT_MAPS
  GENERATE_DEP
  GENERATE_DEP_ONLY
  DEP_PHONY
  SHOW_SLOC
  PROPRIETARY_LICENSE
  SHOW_ANONYMOUS
  ANONYMOUS_REGEX_TRACE
  LOCATION_REGEX_TRACE
  FILE_PER_TYPE
  TYPE_FILE_REGEX_TRACE
  SCHEMA_FILE_REGEX_TRACE
  FAT_TYPE_FILE
)

set(XSD_COMMON_SINGLE_VALUE_ARGUMENTS
  STD # VERSION
  CHAR_TYPE # TYPE
  CHAR_ENCODING # ENC
  OUTPUT_DIR # DIR
  EXTERN_XML_SCHEMA # FILE
  NAMESPACE_MAP # XNS=CNS
  NAMESPACE_REGEX # REGEX
  RESERVED_NAME # N[=R]
  INCLUDE_PREFIX # PREFIX
  INCLUDE_REGEX # REGEX
  GUARD_PREFIX # PREFIX
  HXX_SUFFIX # SUFFIX
  IXX_SUFFIX # SUFFIX
  CXX_SUFFIX # SUFFIX
  FWD_SUFFIX # SUFFIX
  HXX_REGEX # REGEX
  IXX_REGEX # REGEX
  CXX_REGEX # REGEX
  FWD_REGEX # REGEX
  HXX_PROLOGUE # TEXT
  IXX_PROLOGUE # TEXT
  CXX_PROLOGUE # TEXT
  FWD_PROLOGUE # TEXT
  PROLOGUE # TEXT
  HXX_EPILOGUE # TEXT
  IXX_EPILOGUE # TEXT
  CXX_EPILOGUE # TEXT
  FWD_EPILOGUE # TEXT
  EPILOGUE # TEXT
  HXX_PROLOGUE_FILE # FILE
  IXX_PROLOGUE_FILE # FILE
  CXX_PROLOGUE_FILE # FILE
  FWD_PROLOGUE_FILE # FILE
  PROLOGUE_FILE # FILE
  HXX_EPILOGUE_FILE # FILE
  IXX_EPILOGUE_FILE # FILE
  CXX_EPILOGUE_FILE # FILE
  FWD_EPILOGUE_FILE # FILE
  EPILOGUE_FILE # FILE
  EXPORT_SYMBOL # SYMBOL
  DEP_TARGET # TARGET
  DEP_SUFFIX # SUFFIX
  DEP_REGEX # REGEX
  DISABLE_WARNING # WARN
  OPTIONS_FILE # FILE
  SLOC_LIMIT # NUM
  CUSTOM_LITERALS # FILE
  ANONYMOUS_REGEX # REGEX
  LOCATION_MAP # OL=NL
  LOCATION_REGEX # REGEX
  TYPE_FILE_REGEX # REGEX
  SCHEMA_FILE_REGEX # REGEX
  FILE_LIST # FILE
  FILE_LIST_PROLOGUE # TEXT
  FILE_LIST_EPILOGUE # TEXT
  FILE_LIST_DELIM # TEXT
)

set(XSD_TREE_OPTIONS
  GENERATE_POLYMORPHIC
  POLYMORPHIC_TYPE_ALL
  ORDERED_TYPE_DERIVED
  ORDERED_TYPE_MIXED
  ORDERED_TYPE_ALL
  GENERATE_SERIALIZATION
  GENERATE_OSTREAM
  GENERATE_DOXYGEN
  GENERATE_COMPARISON
  GENERATE_DEFAULT_CTOR
  GENERATE_FROM_BASE_CTOR
  SUPPRESS_ASSIGNMENT
  GENERATE_DETACH
  GENERATE_WILDCARD
  GENERATE_ANY_TYPE
  GENERATE_FORWARD
  SUPPRESS_PARSING
  GENERATE_ELEMENT_TYPE
  GENERATE_ELEMENT_MAP
  GENERATE_INTELLISENSE
  OMIT_DEFAULT_ATTRIBUTES
  NAME_REGEX_TRACE
  ROOT_ELEMENT_FIRST
  ROOT_ELEMENT_LAST
  ROOT_ELEMENT_ALL
  ROOT_ELEMENT_NONE
)

set(XSD_TREE_SINGLE_VALUE_ARGUMENTS
  POLYMORPHIC_TYPE # type
  POLYMORPHIC_PLATE # num
  ORDERED_TYPE # typ
  ORDER_CONTAINER # type
  GENERATE_INSERTION # os
  GENERATE_EXTRACTION # is
  TYPE_NAMING # style
  FUNCTION_NAMING # style
  TYPE_REGEX # regex
  ACCESSOR_REGEX # regex
  ONE_ACCESSOR_REGEX # regex
  OPT_ACCESSOR_REGEX # regex
  SEQ_ACCESSOR_REGEX # regex
  MODIFIER_REGEX # regex
  ONE_MODIFIER_REGEX # regex
  OPT_MODIFIER_REGEX # regex
  SEQ_MODIFIER_REGEX # regex
  PARSER_REGEX # regex
  SERIALIZER_REGEX # regex
  CONST_REGEX # regex
  ENUMERATOR_REGEX # regex
  ELEMENT_TYPE_REGEX # regex
  ROOT_ELEMENT # element
  CUSTOM_TYPE # map
  CUSTOM_TYPE_REGEX # regex
  PARTS # num
  PARTS_SUFFIX # suffix
)


set(XSD_PARSER_OPTIONS
  GENERATE_VALIDATION
  SUPPRESS_VALIDATION
  GENERATE_POLYMORPHIC
  GENERATE_NOOP_IMPL
  GENERATE_PRINT_IMPL
  GENERATE_TEST_DRIVER
  FORCE_OVERWRITE
  ROOT_ELEMENT_FIRST
  ROOT_ELEMENT_LAST
)

set(XSD_PARSER_SINGLE_VALUE_ARGUMENTS
  TYPE_MAP # mapfile
  XML_PARSER # parser
  ROOT_ELEMENT # element
  SKEL_TYPE_SUFFIX # suffix
  SKEL_FILE_SUFFIX # suffix
  IMPL_TYPE_SUFFIX # suffix
  IMPL_FILE_SUFFIX # suffix
)
